// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using init.Models;

namespace init.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211217223232_barinak")]
    partial class barinak
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("init.Models.Aid", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("amount")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Aid");

                    b.HasData(
                        new
                        {
                            id = 1,
                            amount = 1
                        });
                });

            modelBuilder.Entity("init.Models.Apikeys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("ApiKey")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Apikeys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApiKey = 5561
                        });
                });

            modelBuilder.Entity("init.Models.SiteUser", b =>
                {
                    b.Property<int>("USERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("COUNTRY")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMAIL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ROLEID")
                        .HasColumnType("int");

                    b.Property<string>("USERNAME")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("USERID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            USERID = 1,
                            COUNTRY = "Turkey",
                            EMAIL = "haci.cingoz@ogr.sakarya.edu.tr",
                            PASSWORD = "123",
                            ROLEID = 1,
                            USERNAME = "g181210086@sakarya.edu.tr"
                        },
                        new
                        {
                            USERID = 2,
                            COUNTRY = "Turkey",
                            EMAIL = "mustafa.kurban@ogr.sakarya.edu.tr",
                            PASSWORD = "123",
                            ROLEID = 1,
                            USERNAME = "g191210056@sakarya.edu.tr"
                        });
                });

            modelBuilder.Entity("init.Models.hayvanlar", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("isim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("katagori")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("yas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("animals");

                    b.HasData(
                        new
                        {
                            id = 1,
                            isim = "Tarçın",
                            katagori = "Köpek",
                            yas = 4
                        },
                        new
                        {
                            id = 2,
                            isim = "Duman",
                            katagori = "Kedi",
                            yas = 2
                        },
                        new
                        {
                            id = 3,
                            isim = "Benekli",
                            katagori = "Kaplumbağa",
                            yas = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
